version: '3'

services:
  bymtask-storage:
    container_name: bym-storage
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: "bym-storage"
      POSTGRES_USER: "bmUSER"
      POSTGRES_PASSWORD: "bmPWD!"
    hostname: "bym-storage"
    ports:
      - "5432:5432"
    volumes:
      - pg-bym-storage-volume:/var/lib/postgresql/data
    networks:
      - elastic

  bymtask-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: bymtask-elastic
    restart: always
    environment:
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
      - discovery.type=single-node
    hostname: bym-elastic
    ports:
      - "9200:9200"
    volumes:
      - pg-bym-elastic-volume:/usr/share/elasticsearch/data
    networks:
      - elastic

  bymtask-logstash:
    build:
      context: logstash
      dockerfile: Dockerfile
    container_name: bymtask-logstash
    volumes:
      - ./logstash/config/.conf:/usr/share/logstash/config/logstash.conf
    ports:
      - "9600:9600"
    depends_on:
      - bymtask-elastic
      - bymtask-storage
    command: logstash -f /usr/share/logstash/config/logstash.conf
    networks:
      - elastic

volumes:
  pg-bym-storage-volume:
  pg-bym-elastic-volume:

networks:
  elastic:
