FROM docker.elastic.co/logstash/logstash:7.16.2

# Download PostgreSQL JDBC driver
RUN curl -o /usr/share/logstash/logstash-core/lib/jars/postgresql.jar https://jdbc.postgresql.org/download/postgresql-42.6.0.jar
